project:
  type: website

website:
  title: "Kun Yang"
  navbar:
    left:
      - text: "About You"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    toc: false